version: '3.9'
services:
    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: infinitymint
        POSTGRES_USER: infinitymint
        POSTGRES_DB: infinitymint
      volumes:
        - pgdata:/var/lib/postgresql/data 
   
    adminer:
      image: adminer
      restart: always
      ports:
        - 8081:8080
   
volumes:
  pgdata: